# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'trondsAzure(9c440e51-4425-4fae-9340-ef853b24d158)'
    subscriptionId: '9c440e51-4425-4fae-9340-ef853b24d158'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RulesEngineDemo'
    location: 'North Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/trstroem/LogicAppVS/blob/master/LogicApp.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/trstroem/LogicAppVS/blob/master/LogicApp.parameters.json'
    deploymentMode: 'Incremental'
